#!/usr/bin/env bash
# Bash script that display 1-100 at multiple 15 'fizzbuzz' 3 'fizz' 5 'buzz'
i=1
while [ $i -le 100 ] 
do
	if [ $((i % 15)) == 0 ];
	then
		echo "fizzBuzz"
	elif [ $((i % 3)) == 0 ];
	then
		echo "fizz"
	elif  [ $((i % 5)) == 0 ];
	then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done 
