#!/usr/bin/env bash
#Bash script that displays the content of a file its username-user id-homedirectory
file="/etc/passwd"

while IFS= read -r line;
do
	echo "$line" | cut -d ":" -f 1,3,6
done <  "$file"
