#!/usr/bin/env bash
# Display content in /etc/passwd
IFS=:
while read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND_SHELL
do 
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in HOME_DIRECTORY and rides $COMMAND/SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER ID INFO"
done < /etc/passwd
