#!/usr/bin/env bash
#Bash script that print loops from 1-10 at 4loop "bad luck" 8loop "good luck.
i=0
while [ $i -le 9 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done

