#!/usr/bin/env bash
#Bash script that displays number from 1-20 at 4 'bad luck from china 9 'bad luck from Japan'
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in 
		4)
			echo 'bad luck from China'
			;;
		9)
			echo 'bad luck from Japan'
			;;
		17)
			echo 'bad luck from Italy'
		esac
		((i++))
done

