#!/usr/bin/env bash
#Bash script that display the time for 12hrs and 59min
i=0
while [ $i -le 12 ];
do
	echo "Hour: $i"
	min=1
	while [ $min -le 59 ];
	do 
		echo "$min"
		((min++))
	done
	((i++))
done
