#!/usr/bin/env bash
# Bash script that configures the server in localhost 
cp /etc/hosts	~/etc/hosts.new
echo "localhost		127.0.0.2" > /etc/hosts
echo "facebook.com	8.8.8.8" > /etc/hosts
cp -f ~/etc/hosts.new	/etc/hosts
